<?php
namespace kr0lik\tree;

use kr0lik\tree\controllers\TreeController;
use kr0lik\tree\controllers\TreeManagerController;
use kr0lik\tree\enum\TreeManagerActionEnum;
use kr0lik\tree\exception\{TreeActionException, TreeManagerModeException, TreeNotFoundException};
use kr0lik\tree\response\TreeResponse;
use kr0lik\tree\traits\BsVersionTrait;
use yii\base\InvalidConfigException;

class TreeManagerAction extends TreeAction
{
    /**
     * @var string
     */
    public $formViewPath = '@kr0lik/tree/views/edit.php';
    /**
     * @var string
     */
    private $formNameField = 'name';
    /**
     * @var string[]|callable
     */
    public $formFields = [];
    /**
     * @var string[]|callable
     */
    public $formLinks = [];

    use BsVersionTrait;

    public function init(): void
    {
        $this->initBsVersion();

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws InvalidConfigException
     */
    protected function validate(): void 
    {
        parent::validate();

        if (!$this->formViewPath) {
            throw new InvalidConfigException('FormViewPath is required.');
        } elseif (!is_string($this->formViewPath)) {
            throw new InvalidConfigException('FormViewPath must be string.');
        }

        if (!$this->formNameField) {
            throw new InvalidConfigException('FormNameField is required.');
        } elseif (!is_string($this->formNameField)) {
            throw new InvalidConfigException('FormNameField must be string.');
        }

        if (!is_array($this->formFields)) {
            throw new InvalidConfigException('FormFields must be array.');
        }
        if ($this->formFields) {
            foreach ($this->formFields as $field) {
                if (!is_string($field) && !is_callable($field)) {
                    throw new InvalidConfigException('FormFields must be array of string (field name) or callable (function (FormActive $form, Model $model): ActiveField { return $form->field(); }).');
                }
            }
        }

        if (!is_array($this->formLinks)) {
            throw new InvalidConfigException('FormLinks must be array.');
        }
        if ($this->formLinks) {
            foreach ($this->formLinks as $link) {
                if (!is_string($link) && !is_callable($link)) {
                    throw new InvalidConfigException('FormLinks must be array of links (ex: Html::a()) or callable (function (Model $model): string { return Html::a(); }).');
                }
            }
        }
    }

    /**
     * @throws TreeActionException
     * @throws TreeManagerModeException
     * @throws TreeNotFoundException
     */
    protected function runAction(string $action): TreeResponse
    {
        switch ($action) {
            case TreeManagerActionEnum::GET_FORM:
                return $this->getController()->getFormAction(
                    $this->formViewPath,
                    $this->formNameField,
                    $this->formFields,
                    $this->formLinks,
                    $this->bsCssClasses, // From BsVersionTrait
                );
            case TreeManagerActionEnum::VALIDATE:
                return $this->getController()->validateAction();
            case TreeManagerActionEnum::CREATE:
                return $this->getController()->createAction();
            case TreeManagerActionEnum::UPDATE:
                return $this->getController()->updateAction();
            case TreeManagerActionEnum::DELETE:
                return $this->getController()->deleteAction();
            case TreeManagerActionEnum::MOVE:
                return $this->getController()->moveAction();
            default:
                return parent::runAction($action);
        }
    }

    /**
     * @throws TreeManagerModeException
     */
    protected function getController(): TreeController
    {
        $repository = $this->getRepository();
        
        return new TreeManagerController($this->controller, $repository);
    }
}
